In [1]:
!pip install spacy
!pip install pandas
!pip install -U pip setuptools wheel
!python -m spacy download en_core_web_sm
!pip install openpyxl
!pip install scikit-learn
!pip install gensim

     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --------------------------------------- 0.0/12.8 MB 330.3 kB/s eta 0:00:39
     --------------------------------------- 0.0/12.8 MB 281.8 kB/s eta 0:00:46
     --------------------------------------- 0.1/12.8 MB 525.1 kB/s eta 0:00:25
      -------------------------------------- 0.2/12.8 MB 748.1 kB/s eta 0:00:17
      -------------------------------------- 0.3/12.8 MB 927.4 kB/s eta 0:00:14
     - -------------------------------------- 0.4/12.8 MB 1.3 MB/s eta 0:00:10
     - -------------------------------------- 0.6/12.8 MB 1.6 MB/s eta 0:00:08
     -- ------------------------------------- 0.7/12.8 MB 1.8 MB/s eta 0:00:07
     -- ------------------------------------- 0.9/12.8 MB 2.0 MB/s eta 0:00:07
     --- ------------------------------------ 1.0/12.8 MB 2.1 MB/s eta 0:00:06
     --- ------------------------------------ 1.2/12.8 MB 2.2


[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import spacy
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec
from scipy.sparse import lil_matrix

### **Preprocessing the text**
The steps will be: 
* Tokenization
* Lemmatization
* Cleaning the Lemmatized tokens

In [3]:
nlp = spacy.load('en_core_web_sm')

*Functions (using spaCy) for Tokenization, Lemmatization & Cleaning*

In [4]:
def tokenize_spacy(text):
    doc = nlp(text)
    return [token.text for token in doc]

def lemmatize_spacy(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc]

def clean_text_spacy(tokens):
    cleaned_tokens = [token.lower() for token in tokens if token.isalpha()]
    return cleaned_tokens

*We will be using a Whatsapp conversation as our corpus*

In [5]:
with open('_chat.txt', 'r', encoding='utf-8') as file:
    content = file.read()

data = []
for row in content.split('\n'):
    data.append(row[row.rfind(':') + 1:])

whatsapp_df = pd.DataFrame({"whatsapp_text":data})

*Applying Tokenization*

In [6]:
whatsapp_df['scraped_tokens'] = whatsapp_df['whatsapp_text'].apply(tokenize_spacy)

*Applying Lemmatization*

In [7]:
whatsapp_df['scraped_lemmatization'] = whatsapp_df['whatsapp_text'].apply(lemmatize_spacy)

*Cleaning the lemmatized tokens*

In [8]:
whatsapp_df['cleaned_tokens'] = whatsapp_df['scraped_lemmatization'].apply(clean_text_spacy)

### **Remove Stop Words**

In [9]:
def remove_stop_words(tokens):
    stop_words = nlp.Defaults.stop_words
    filtered_tokens = [token for token in tokens if token not in stop_words]
    return filtered_tokens

In [10]:
whatsapp_df['filtered_tokens'] = whatsapp_df['cleaned_tokens'].apply(remove_stop_words)

In [11]:
whatsapp_df_copy = whatsapp_df.copy()
whatsapp_df_copy['filtered_tokens'] = whatsapp_df_copy['filtered_tokens'].apply(lambda x: ' '.join(x))
whatsapp_df_copy.to_excel('whatsapp_df.xlsx')
whatsapp_df_copy.head()

whatsapp_text  \
0   ‎Messages and calls are end-to-end encrypted....   
1                ‎You created group “מדברים באנגלית”   
2                              hey noam how are you?   
3                Hey!! I’m good thanks how about you   
4                     What are you going to do today   

                                      scraped_tokens  \
0  [ , ‎Messages, and, calls, are, end, -, to, -,...   
1   [ , ‎You, created, group, “, מדברים, באנגלית, ”]   
2                   [ , hey, noam, how, are, you, ?]   
3  [ , Hey, !, !, I, ’m, good, thanks, how, about...   
4          [ , What, are, you, going, to, do, today]   

                               scraped_lemmatization  \
0  [ , ‎message, and, call, be, end, -, to, -, en...   
1    [ , ‎you, create, group, ", מדברים, באנגלית, "]   
2                    [ , hey, noam, how, be, you, ?]   
3  [ , Hey, !, !, I, ’m, good, thank, how, about,...   
4              [ , what, be, you, go, to, do, today]   

                                      cleaned_tokens  \
0  [and, call, be, end, to, end, encrypt, no, one...   
1                   [create, group, מדברים, באנגלית]   
2                          [hey, noam, how, be, you]   
3             [hey, i, good, thank, how, about, you]   
4                 [what, be, you, go, to, do, today]   

                                     filtered_tokens  
0  end end encrypt outside chat whatsapp read listen  
1                        create group מדברים באנגלית  
2                                           hey noam  
3                                     hey good thank  
4                                              today

### **Applying Feature Extraction by the following algorithms:**
* BOW
* TF-IDF
* Word embedding by WORD2VEC

**Bow algorithm**

In [12]:
def bow_extraction(texts):
    vectorizer = CountVectorizer()
    X = vectorizer.fit_transform(texts)
    return X.toarray(), vectorizer.get_feature_names_out()

In [13]:
bow_features, bow_feature_names = bow_extraction(whatsapp_df_copy['filtered_tokens'])
print("BoW Features:\n", bow_features)
print("Feature Names:\n", bow_feature_names)

BoW Features:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Feature Names:
 ['actually' 'add' 'afeka' 'ai' 'amazing' 'analysis' 'anytime' 'article'
 'ask' 'awesome' 'backend' 'bad' 'balance' 'balcony' 'basil' 'beach'
 'beautiful' 'believe' 'big' 'bit' 'board' 'book' 'brightly' 'bump'
 'bunch' 'busy' 'care' 'case' 'catch' 'challenge' 'change' 'character'
 'chat' 'check' 'child' 'clever' 'coffee' 'come' 'conversation' 'cooking'
 'cool' 'couple' 'course' 'cream' 'create' 'curious' 'currently' 'day'
 'debug' 'deck' 'deep' 'definitely' 'detective' 'development' 'difference'
 'dive' 'drag' 'early' 'easy' 'eat' 'edit' 'emma' 'encrypt' 'end'
 'enhance' 'excited' 'exercise' 'exist' 'exit' 'fantastic' 'far'
 'fascinating' 'finally' 'finish' 'forget' 'forward' 'fresh' 'friend'
 'fun' 'game' 'gang' 'garden' 'gardening' 'generate' 'good' 'got' 'gpt'
 'great' 'gripping' 'ground' 'group' 'grow' 'haha' 'hand' 'hangover'
 'harar

**TF-IDF algorithm**

In [14]:
def tfidf_extraction(texts):
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(texts)
    return X.toarray(), vectorizer.get_feature_names_out()

In [15]:
tfidf_features, tfidf_feature_names = tfidf_extraction(whatsapp_df_copy['filtered_tokens'])
print("TF-IDF Features:\n", tfidf_features)
print("Feature Names:\n", tfidf_feature_names)

TF-IDF Features:
 [[0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.5 0.5]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]]
Feature Names:
 ['actually' 'add' 'afeka' 'ai' 'amazing' 'analysis' 'anytime' 'article'
 'ask' 'awesome' 'backend' 'bad' 'balance' 'balcony' 'basil' 'beach'
 'beautiful' 'believe' 'big' 'bit' 'board' 'book' 'brightly' 'bump'
 'bunch' 'busy' 'care' 'case' 'catch' 'challenge' 'change' 'character'
 'chat' 'check' 'child' 'clever' 'coffee' 'come' 'conversation' 'cooking'
 'cool' 'couple' 'course' 'cream' 'create' 'curious' 'currently' 'day'
 'debug' 'deck' 'deep' 'definitely' 'detective' 'development' 'difference'
 'dive' 'drag' 'early' 'easy' 'eat' 'edit' 'emma' 'encrypt' 'end'
 'enhance' 'excited' 'exercise' 'exist' 'exit' 'fantastic' 'far'
 'fascinating' 'finally' 'finish' 'forget' 'forward' 'fresh' 'friend'
 'fun' 'game' 'gang' 'garden' 'gardening' 'generate' 'good' 'got' 'gpt'
 

**Word Embeddings by Word2Vec**

In [16]:
def word2vec_extraction(tokens_list, vector_size=100, window=5, min_count=1, workers=4):
    model = Word2Vec(sentences=tokens_list, vector_size=vector_size, window=window, min_count=min_count, workers=workers)
    return model

In [17]:
tokenized_texts = [text.split() for text in whatsapp_df_copy['filtered_tokens']]

word2vec_model = word2vec_extraction(tokenized_texts)
similar_words = word2vec_model.wv.most_similar('finish')
print(similar_words)

[('relax', 0.22336749732494354), ('enhance', 0.22177574038505554), ('system', 0.19541819393634796), ('forget', 0.19149678945541382), ('miss', 0.19064918160438538), ('character', 0.1868743598461151), ('kind', 0.17510007321834564), ('noah', 0.1748739331960678), ('plus', 0.1747390180826187), ('debug', 0.16881349682807922)]


## **Glove Explanation**

GloVe (Global Vectors for Word Representation) is an unsupervised learning algorithm for obtaining vector representations (embeddings) for words. These embeddings capture semantic relationships between words based on their co-occurrence statistics in a large corpus of text. Unlike Word2Vec, which learns embeddings by predicting context words given a target word (skip-gram model) or predicting a target word given context words (continuous bag of words model), GloVe learns embeddings by factorizing the word co-occurrence matrix.

Explanation of GloVe:
* Co-occurrence Matrix: GloVe starts with a word-word co-occurrence matrix where each element 
𝑋𝑖𝑗 ​represents how often word 𝑗 appears in the context of word 𝑖 within a fixed window size.

* Objective: The goal of GloVe is to learn word embeddings such that the dot product of two word vectors corresponds to the logarithm of their co-occurrence probability.

* Training: GloVe uses stochastic gradient descent to minimize a loss function that measures the discrepancy between the dot product of word vectors and the logarithm of their co-occurrence probabilities.

* Advantages: GloVe embeddings tend to capture global semantic meanings better than some other models, and they often perform well in tasks requiring understanding of word relationships and analogies.

In [18]:
def build_cooccurrence_matrix(corpus, window_size=2):
    vocab = list(set(corpus))
    word_to_id = {word: i for i, word in enumerate(vocab)}
    cooccurrence = lil_matrix((len(vocab), len(vocab)), dtype=np.float64)
    
    for i, word in enumerate(corpus):
        left_context = max(0, i - window_size)
        right_context = min(len(corpus), i + window_size + 1)
        for j in range(left_context, right_context):
            if i != j:
                cooccurrence[word_to_id[word], word_to_id[corpus[j]]] += 1
    
    return cooccurrence.tocsr(), word_to_id

def glove_loss(X, W, U, b, c):
    diff = W.dot(U.T) + b[:, np.newaxis] + c[np.newaxis, :] - np.log(X.toarray() + 1)
    squared_error = np.sum(diff ** 2)
    return squared_error

def train_glove(X, vector_size=50, iterations=50, learning_rate=0.01):
    vocab_size = X.shape[0]
    W = np.random.randn(vocab_size, vector_size) / np.sqrt(vector_size)
    U = np.random.randn(vocab_size, vector_size) / np.sqrt(vector_size)
    b = np.zeros(vocab_size)
    c = np.zeros(vocab_size)
    
    for iteration in range(iterations):
        error = glove_loss(X, W, U, b, c)
        if iteration % 10 == 0:
            print(f"Iteration {iteration}: Loss = {error}")
        
        # Compute gradients
        diff = W.dot(U.T) + b[:, np.newaxis] + c[np.newaxis, :] - np.log(X.toarray() + 1)
        grad_W = 2 * diff.dot(U)
        grad_U = 2 * diff.T.dot(W)
        grad_b = 2 * np.sum(diff, axis=1)
        grad_c = 2 * np.sum(diff, axis=0)
                
        # Update parameters
        W -= learning_rate * grad_W
        U -= learning_rate * grad_U
        b -= learning_rate * grad_b
        c -= learning_rate * grad_c
    
    return (W + U) / 2

In [19]:
corpus = []
for sentence in whatsapp_df_copy['filtered_tokens']:
    for word in sentence.split(' '):
        corpus.append(word)

In [20]:
X, word_to_id = build_cooccurrence_matrix(corpus)
word_vectors = train_glove(X, vector_size=5, iterations=1000, learning_rate=0.001)

Iteration 0: Loss = 10813.924315876615
Iteration 10: Loss = 1763.977827187113
Iteration 20: Loss = 1051.5035496490389
Iteration 30: Loss = 850.5703121914399
Iteration 40: Loss = 768.8830422611537
Iteration 50: Loss = 729.1541170285084
Iteration 60: Loss = 707.5929587796551
Iteration 70: Loss = 694.924093814273
Iteration 80: Loss = 686.9770883930474
Iteration 90: Loss = 681.6932304954524
Iteration 100: Loss = 677.9854997460309
Iteration 110: Loss = 675.2482256747436
Iteration 120: Loss = 673.127778079459
Iteration 130: Loss = 671.40867098846
Iteration 140: Loss = 669.9542759575444
Iteration 150: Loss = 668.6747088007278
Iteration 160: Loss = 667.5087978801464
Iteration 170: Loss = 666.4136157264198
Iteration 180: Loss = 665.3582131209791
Iteration 190: Loss = 664.3197674137193
Iteration 200: Loss = 663.2811643425039
Iteration 210: Loss = 662.2294586636441
Iteration 220: Loss = 661.154889391882
Iteration 230: Loss = 660.0502530134871
Iteration 240: Loss = 658.9105100384893
Iteration 250:

In [21]:
for word, idx in word_to_id.items():
    print(f"{word}: {word_vectors[idx]}")

: [ 0.32666741  0.39292591 -0.02530403  0.23449565 -0.616863  ]
plus: [0.10353349 0.03651708 0.14362765 0.03163492 0.02704779]
ai: [-0.07670163  0.10681701 -0.03908815 -0.09864592 -0.02434656]
outside: [0.02235492 0.03203921 0.14403791 0.08965167 0.00115693]
herb: [ 3.47237382e-01 -2.70955891e-04  2.79774697e-01 -8.88353083e-02
  2.37845377e-01]
kid: [-0.06668165  0.08972566 -0.11288273 -0.03213694 -0.01996813]
big: [ 0.02049489  0.06107098 -0.01281123 -0.04079905 -0.01684504]
pick: [ 0.14021226  0.11219466 -0.02114077  0.19588986  0.0632673 ]
soon: [ 0.20448831 -0.39435108 -0.64473148  0.01340299 -0.15467205]
coffee: [ 0.01650865 -0.07738149 -0.22091133  0.0817644  -0.01485897]
recommendation: [ 0.14880396  0.15887051  0.10530181  0.03986618 -0.01454931]
ground: [ 0.00444902  0.06616211  0.09233331 -0.0977379  -0.00430867]
child: [-0.02086532  0.01537468  0.06424978  0.00637407 -0.03126026]
sound: [-0.50396917 -0.38282752  0.22546679 -0.07241472  0.02906594]
grow: [ 0.00273331 -0.0065

### **Explanation of applying GloVe:**
*Loss Over Iterations:*
The loss values decrease over iterations, indicating that the model is learning and optimizing the word vectors effectively.
The loss decreases significantly in the early iterations and continues to decrease at a slower rate as training progresses. This indicates that the model is converging towards an optimal set of word vectors.

*Word Vectors:*
The final word vectors are the main output of the GloVe algorithm. Each word in your dataset is represented by a vector in a multi-dimensional space.
Each vector captures the semantic properties of the corresponding word. Words with similar meanings or usage patterns tend to have similar vector representations.

### **Applying tagging by CYK**

We are asked to apply the CYK tagging to 5 sentences, 1 manually and 4 with code.
The manual cyk tagging is in the attached word file. 

In [22]:
def cyk_parse(sentence, grammar):
    # Step 1: Tokenization
    tokens = sentence.split()
    n = len(tokens)
    table = [[set() for _ in range(n+1)] for _ in range(n+1)]
	
    # Step 2: Initialization
    for i in range(1, n+1):
        for rule in grammar:
            if rule[1] == tokens[i-1]:
                table[i][i].add(rule[0])

    # Step 3: Rule Application
    for length in range(2, n+1):
        for i in range(1, n-length+2):
            j = i + length - 1
            for k in range(i, j):
                for rule in grammar:
                    if len(rule) == 3:
                        for left in table[i][k]:
                            for right in table[k+1][j]:
                                if rule[1] in left and rule[2] in right:
                                    table[i][j].add(rule[0])


    # Step 4: Backtracking
    if 'S' in table[1][n]:
        return True, table
    else:
        return False, table

In [23]:
# sentences that will be parsed
sentence_1 = whatsapp_df_copy['whatsapp_text'][19] # early today was a beautiful day
sentence_2 = whatsapp_df_copy['whatsapp_text'][20] # the sun shone brightly warming the ground
sentence_3 = whatsapp_df_copy['whatsapp_text'][21] # I went to the beach with a friend
sentence_4 = whatsapp_df_copy['whatsapp_text'][22] # the children ate ice-cream

sentences = [sentence_1, sentence_2, sentence_3, sentence_4]

In [24]:
# Define the context-free grammar in CNF
grammar_1 = [
    ('S', 'NP', 'VP'),
    ('NP', 'RB', 'NN'),
    ('NP', 'DT', 'NPA'),
    ('NPA', 'JJ', 'NN'),
    ('RB', 'early'),
    ('NN', 'today'),
    ('VP', 'VBD', 'NP'),
    ('VBD', 'was'),
    ('DT', 'a'),
    ('JJ', 'beautiful'),
    ('NN', 'day')
]

grammar_2 = [
    ('S', 'NP', 'VP'),
    ('NP', 'DT', 'NN'),
    ('DT', 'the'),
    ('NN', 'sun'),
    ('VP', 'VBD', 'S'),
    ('VBD', 'shone'),
    ('S', 'RB', 'VP'),
    ('RB', 'brightly'),
    ('VP', 'VBG', 'NP'),
    ('VBG', 'warming'),
    ('DT', 'the'),
    ('NN', 'ground')
]

grammar_3 = [
    ('S', 'NP', 'VP'),
    ('NP', 'I'),
    ('VP', 'VBD', 'VP_0'),
    ('VP_0', 'PP', 'PP'),
    ('VBD', 'went'),
    ('PP', 'IN', 'NP'),
    ('IN', 'to'),
    ('IN', 'with'),
    ('NP', 'DT', 'NN'),
    ('DT', 'the'),
    ('DT', 'a'),
    ('NN', 'beach'),
    ('NN', 'friend')
]

grammar_4 = [
    ('S', 'NP', 'VP'),
    ('NP', 'DT', 'NN'),
    ('NN', 'children'),
    ('DT', 'the'),
    ('VP', 'VBD', 'NN'),
    ('VBD', 'ate'),
    ('NN', 'ice-cream')
]

grammars = [grammar_1, grammar_2, grammar_3, grammar_4]

In [25]:
# Call the CYK parser for each sentence
for sentence, grammar in zip(sentences, grammars):
    parsed, table = cyk_parse(sentence, grammar)

    # Print the parse table and whether the sentence was parsed or not
    if parsed:
        print("Input sentence: ", sentence)
        print("Parse table: ")
        for row in table:
            print(row)
    else:
        print("Input sentence: ", sentence)
        print("Sentence not parsed.")
    print('\n')

Input sentence:   early today was a beautiful day
Parse table: 
[set(), set(), set(), set(), set(), set(), set()]
[set(), {'RB'}, {'NP'}, set(), set(), set(), {'S'}]
[set(), set(), {'NN'}, set(), set(), set(), set()]
[set(), set(), set(), {'VBD'}, set(), set(), {'VP'}]
[set(), set(), set(), set(), {'DT'}, set(), {'NP'}]
[set(), set(), set(), set(), set(), {'JJ'}, {'NPA'}]
[set(), set(), set(), set(), set(), set(), {'NN'}]


Input sentence:   the sun shone brightly warming the ground
Parse table: 
[set(), set(), set(), set(), set(), set(), set(), set()]
[set(), {'DT'}, {'NP'}, set(), set(), set(), set(), {'S'}]
[set(), set(), {'NN'}, set(), set(), set(), set(), set()]
[set(), set(), set(), {'VBD'}, set(), set(), set(), {'VP'}]
[set(), set(), set(), set(), {'RB'}, set(), set(), {'S'}]
[set(), set(), set(), set(), set(), {'VBG'}, set(), {'VP'}]
[set(), set(), set(), set(), set(), set(), {'DT'}, {'NP'}]
[set(), set(), set(), set(), set(), set(), set(), {'NN'}]


Input sentence:   I went to